development:
  adapter: postgresql
  encoding: unicode
  database: drive_dev
  host: localhost
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: drive_dev
  host: localhost
  pool: 5
  username: postgres
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: drive_dev
  host: localhost
  pool: 5
  username: postgres
  password: root