# For development environment
development:
  adapter: postgresql
  encoding: unicode
  database: drive_dev
  host: localhost
  pool: 5
  username: postgres
  password: root

# For test environment
test:
  adapter: postgresql
  encoding: unicode
  database: drive_dev
  host: localhost
  pool: 5
  username: postgres
  password: root

# For production environment
production:
  adapter: mysql2
  encoding: utf8
  database: drive_dev
  host: 127.0.0.1
  username: postgres
  password: root
  port: 3306
  secure_auth: false

# For staging environment
staging:
  adapter: mysql2
  encoding: utf8
  database: drive_dev
  host: 127.0.0.1
  username: postgres
  password: root
  port: 3306
  secure_auth: false

# For heroku environment
preview:
  adapter: postgresql
  encoding: unicode
  database: drive_dev
  host: localhost
  pool: 5
  username: postgres
  password: root