app_name: 'ArrivaDrive'
default_password: 'password'

pagination:
  per_page: 10
  events_per_page: 3

# Pagination for participants
participants:
  pagination:
    per_page: 4

defaults:
  date_format_in_views: '%d/%m/%Y'
  i_cal_event_finish_time: 17
  participant_home_screen_video: 'http://www.youtube.com/embed/uaynHY00A1c'

paperclip:
  style:
    medium: '300x300'
    thumb: '100x100'
    activity:
      small: '55x55'
  image_path: '/system/:class/:photos/:id/:style/:basename.:extension'

mail:
  default_url_options:
    support_email: 'support@arrivedrive.in'
    web_url: 'http://intense-island-1282.herokuapp.com/'
    mail_to: 'reevec@arriva.co.uk'
    contact: '+44 7584 393 586'
    contact_email: 'support@drivedb.net'

field_length_limit:
  performance_summary: 250
  event_description: 200
  activity_description: 200

activity_points:
  review_completion: 300
  correct_mcq_answer: 100
  write_note: 25

participant_attachments:
  paperclip: { path: ":rails_root/public/system/participant_attachments/:id/:filename", url: "/system/participant_attachments/:id/:filename" }

event_attachments:
  paperclip: { path: ":rails_root/public/system/event_attachments/:id/:filename", url: "/system/event_attachments/:id/:filename" }

participant_attachment_path_for_email:
  attachment_path: 'public/system/participant_attachments'