app_name: 'ArrivaDrive'
default_password: 'password'

pagination:
  per_page: 10
  events_per_page: 3

# Pagination for participants
participants:
  pagination:
    per_page: 4

defaults:
  date_format_in_views: '%d/%m/%Y'

paperclip:
  style:
    medium: '300x300'
    thumb: '100x100'
    activity:
      small: '55x55'
  image_path: '/system/:class/:photos/:id/:style/:basename.:extension'

mail:
  default_url_options:
    support_email: 'support@arrivedrive.in'

field_length_limit:
  performance_summary: 250
  event_description: 200
  activity_description: 200

activity_points:
  review_completion: 300
  correct_mcq_answer: 100
  write_note: 25
